pub mod chat_client;
pub mod client;
pub mod config;
pub mod http;
pub mod llamacpp;
pub mod ollama;
pub mod parser;
pub mod protocol;
pub mod request;
pub mod response;

pub use chat_client::{ChatClient, ChatWireMessage};
pub use client::ApiClient;
pub use config::{Auth, ClientConfig};
pub use http::HttpClient;
pub use llamacpp::{LlamaCppClient, LlamaCppMessage, LlamaCppModel};
pub use ollama::{ChatStreamEvent, OllamaClient, OllamaMessage, OllamaModel, RawToolCall};
pub use parser::{ParsedRequest, parse_hurl, parse_hurl_multi};
pub use protocol::Protocol;
pub use request::{ApiRequest, Method};
pub use response::ApiResponse;
